settings:
  common: 
    agile:        true
    employer:     true
    description:  true
    relations:    true
    language:     true
    architecture: true
    stack:        true
    technology:   true
    environment:  true
    keywords:     keywords.md
    platform:     platform.md
  parser: 
    agile:            key-multi-value
    employer:         struct
    description:      key-value
    matches:          line
    relations:        key-list
    language:         key-multi-value
    architecture:     key-multi-value
    stack:            key-list-key
    technology:       key-multi-value
    environment:      key-multi-value
    keywords:         key-multi-vkeywords.md
    platform:         key-multi-vplatform.md
  data-file: 
    agile:        agile.md
    employer:     employer.md
    description:  description.md
    relations:    relations.md
    language:     language.md
    architecture: architecture.md
    stack:        stack.md
    technology:   technology.md
    environment:  environment.md
    keywords:     keywords.md
    platform:     platform.md